# Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
# CircleCI maintains a library of pre-built images
# documented at https://circleci.com/docs/2.0/circleci-images/
#
# How to add a status badge
# https://circleci.com/docs/2.0/status-badges/
#
# Continuous Integration with CircleCI and NodeJS
# https://medium.com/meshstudio/continuous-integration-with-circleci-and-nodejs-44c3cf0074a0
#
# How to add a status badge
# https://circleci.com/docs/2.0/status-badges/

version: 2
jobs:
  build:
    docker:
      — image: circleci/node:latest
    working_directory: ~/repo
    steps:
        — checkout # special step to check out source code to working directory
          - run:
          name: npm install
          command: npm install
          — run:
            name: npm test
            command: npm test